galaxy_info:
  author: Justin Herron
  description: your role description
  company: your company (optional)
  issue_tracker_url: http://example.com/issue/tracker
  license: CC-BY-4.0
  min_ansible_version: 2.1
