- name: gpg-agent.service
  state: started
  scope: user
  enabled: true
- name: gpg-agent.socket
  state: started
  scope: user
  enabled: true
- name: gpg-agent-browser.socket
  state: started
  scope: user
  enabled: true
- name: gpg-agent-extra.socket
  state: started
  scope: user
  enabled: true
- name: gpg-agent-ssh.socket
  state: started
  scope: user
  enabled: true
